name: External Site Post Handler

on:
  push:
    branches:
      - main

jobs:
  process_external_post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Extract text from POST request body
        id: extract_text
        run: |
          echo "Extracting text from POST request body..."
          text=$(jq -r '.text' $GITHUB_EVENT_PATH)
          echo "::set-output name=text::$text"

      - name: Add text to second line of specified file
        run: |
          echo "Adding text to second line of specified file..."
          file_path="path/to/file.txt"
          sed -i "2i ${extract_text}" "$file_path"

      - name: Commit changes
        run: |
          echo "Committing changes..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add text to second line of file"
          git push
