name: Update File on Post Request

on:
  repository_dispatch:
    types: [post-request]

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read request body from input file
        run: echo "::set-env name=BODY::$(< $GITHUB_EVENT_PATH)"

      - name: Append data to file
        run: |
          BODY=$(echo $BODY | tr -d '\r')
          sed -i '2s/$/ '"$BODY"'/' ipShow.js
        shell: bash
